### ISSUE TITLE
run from random container name

### ISSUE THREAD

**Issue by dlbewley** [tiredofit/docker-gcds#1]
I'm trying to do something similar to what you've done, but I'm shooting for a more ephemeral runtime. OpenShift. I've made changes to update the password in the XML based on your script, but during testing I'm running into:

```
bash-4.2$ $APP_DIR/GoogleCloudDirSync/upgrade-config -testldap -c "$GCDS_SYNC_CONFIG"
[2017-10-11 00:25:29,239] [main] [WARN] [usersyncapp.cli.UpgradeConfig] Upgrading configuration file "/opt/app-root/etc/test_config.xml" to most recent version (will save a backup).
com.google.usersyncapp.plugin.InvalidPluginConfigurationException: Please update the LDAP password in the Configuration Manager and save the configuration file.


It is possible that this configuration file was created on a different system, so encrypted information stored in it can't be decrypted. Please use the Configuration Manager to update your details in the 'LDAP Configuration' section. Use the 'Test Connection' button to ensure that connection settings is set up correctly. For more information, visit http://support.google.com/a/bin/answer.py?hl=en&answer=3075991.

ExceptionDetails : [authCredentialsEncrypted] contains an invalid encrypted value
        at com.google.usersyncapp.plugin.ldap.LdapConfigLoader.loadFromElement(LdapConfigLoader.java:718)
        at com.google.usersyncapp.plugin.ldap.LdapConfigLoader.load(LdapConfigLoader.java:74)
        at com.google.usersyncapp.plugin.ldap.LDAPPlugin.setConfiguration(LDAPPlugin.java:288)
        at com.google.usersyncapp.sync.PluginFactory.initializePlugin(PluginFactory.java:105)
        at com.google.usersyncapp.sync.PluginFactory.initializeFromPluginConfigList(PluginFactory.java:131)
        at com.google.usersyncapp.sync.PluginFactory.initializePluginsIntoGroup(PluginFactory.java:161)
        at com.google.usersyncapp.cli.UpgradeConfig.upgrade(UpgradeConfig.java:134)
        at com.google.usersyncapp.cli.UpgradeConfig.main(UpgradeConfig.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
```

Do you know if other fields beyond the `authCredentialsEncrypted` need to be replaced when moving to another machine?

**Comment by tiredofit** [comment]
Hi, sorry about the delay.
The encrypted password is an interesting one and there is quite a lot of hacks in place in the startup script (/etc/s6/services/10-gcds/run) to make that happen. What this image does is generate the encrypted password manually upon startup based on your GCDS_PASS and then rewrites the XML file with that information. Making the XML file off the GCDS Desktop app and then dropping it into place will not work as there is some sort of hardware/host fingerprinting. 

GCDS is a tricky / finnicky tool, especially with this image where it also needs an additional OAUTH step, but was the only way I was able to containzerize it.

**Comment by dlbewley** [comment]
Thanks for the comments! Yea I think I'm just going to dedicate a VM to this.
